runtime: python310   # Use supported Python version
service: my-first-service   # Custom service name
instance_class: F1
automatic_scaling:
  min_instances: 1
  max_instances: 5
handlers:
  - url: /.*
    script: auto
